import { useState, useRef, useEffect } from "react";

// ── Markdown generation (client-side) ──────────────────────────────────

export function generateMarkdown(reviewResult, repoMeta, lang = "en") {
  const isEn = lang === "en";
  const t = (en, pt) => isEn ? en : pt;

  const r = reviewResult.report;
  const stats = r.stats || {};
  const issues = r.issues || [];
  const ctx = reviewResult.context || {};
  const timings = reviewResult.timings || {};
  const totalTime = Object.values(timings).reduce((a, b) => a + b, 0);

  const lines = [];
  lines.push(`# ${t("Code Review Report", "Relatório de Code Review")}`);
  lines.push("");
  lines.push(`**${t("Repository", "Repositório")}:** ${repoMeta?.path || "—"}`);
  lines.push(`**${t("Generated by", "Gerado por")}:** RepoMind`);
  lines.push(`**${t("Date", "Data")}:** ${new Date().toLocaleString()}`);
  lines.push("");
  lines.push("---");
  lines.push("");

  // Verdict
  lines.push(`## ${t("Verdict", "Veredicto")}`);
  lines.push("");
  if (r.approved) {
    lines.push(`✅ **${t("APPROVED", "APROVADO")}**`);
  } else {
    lines.push(`❌ **${t("CHANGES REQUIRED", "MUDANÇAS NECESSÁRIAS")}**`);
  }
  lines.push("");
  lines.push(r.overall_verdict || "");
  lines.push("");

  // Stats
  lines.push(`## ${t("Statistics", "Estatísticas")}`);
  lines.push("");
  lines.push(`| ${t("Severity", "Severidade")} | ${t("Count", "Quantidade")} |`);
  lines.push("|---|---|");
  lines.push(`| 🔴 Critical | ${stats.critical || 0} |`);
  lines.push(`| 🟠 Major | ${stats.major || 0} |`);
  lines.push(`| 🟡 Minor | ${stats.minor || 0} |`);
  lines.push(`| 🟢 Suggestion | ${stats.suggestion || 0} |`);
  lines.push(`| ⚪ ${t("Filtered by Critic", "Filtrados pelo Critic")} | ${stats.filtered_by_critic || 0} |`);
  lines.push(`| **${t("Total validated", "Total validado")}** | **${stats.total || 0}** |`);
  lines.push("");

  // Pipeline
  lines.push(`## ${t("Pipeline Execution", "Execução do Pipeline")}`);
  lines.push("");
  lines.push(`${t("Total time", "Tempo total")}: **${totalTime.toFixed(2)}s**`);
  lines.push("");
  for (const [stage, time] of Object.entries(timings)) {
    lines.push(`- **${stage}**: ${time.toFixed(2)}s`);
  }
  lines.push("");

  // Context
  if (ctx.files && ctx.files.length > 0) {
    lines.push(`## ${t("Context retrieved", "Contexto recuperado")}`);
    lines.push("");
    lines.push(t(
      `RAG retrieved ${ctx.files.length} files from the project to inform the review:`,
      `O RAG recuperou ${ctx.files.length} arquivos do projeto para informar o review:`
    ));
    lines.push("");
    for (const f of ctx.files.slice(0, 10)) {
      lines.push(`- \`${f}\``);
    }
    lines.push("");
  }

  // Issues
  if (issues.length > 0) {
    lines.push(`## ${t("Issues", "Issues")} (${issues.length})`);
    lines.push("");

    const bySeverity = ["critical", "major", "minor", "suggestion"];
    for (const sev of bySeverity) {
      const sevIssues = issues.filter(i => i.severity === sev);
      if (sevIssues.length === 0) continue;

      const sevEmoji = { critical: "🔴", major: "🟠", minor: "🟡", suggestion: "🟢" }[sev];
      lines.push(`### ${sevEmoji} ${sev.toUpperCase()}`);
      lines.push("");

      for (const issue of sevIssues) {
        lines.push(`#### \`${issue.file}\`${issue.line ? `:${issue.line}` : ""}`);
        lines.push("");
        lines.push(`**${issue.description}**`);
        lines.push("");
        if (issue.justification) {
          lines.push(`**${t("Justification", "Justificativa")}:** ${issue.justification}`);
          lines.push("");
        }
        if (issue.suggestion) {
          lines.push(`**${t("Suggestion", "Sugestão")}:**`);
          lines.push("");
          lines.push("```");
          lines.push(issue.suggestion);
          lines.push("```");
          lines.push("");
        }
        if (issue.category) {
          lines.push(`*${t("Category", "Categoria")}: ${issue.category}*`);
          lines.push("");
        }
        lines.push("---");
        lines.push("");
      }
    }
  } else {
    lines.push(`## ${t("Issues", "Issues")}`);
    lines.push("");
    lines.push(t("No issues found.", "Nenhum issue encontrado."));
    lines.push("");
  }

  lines.push("");
  lines.push("---");
  lines.push("");
  lines.push(t(
    "_Generated by [RepoMind](https://github.com) — Context-aware AI code review_",
    "_Gerado por [RepoMind](https://github.com) — Code review com AI contextual_"
  ));

  return lines.join("\n");
}


// ── Download helpers ──────────────────────────────────────────────────

function downloadFile(content, filename, mimeType) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 100);
}


// ── ExportMenu component ───────────────────────────────────────────────

export default function ExportMenu({ reviewResult, repoMeta, lang, t, accent = "#e8400c" }) {
  const [open, setOpen] = useState(false);
  const [exporting, setExporting] = useState(false);
  const ref = useRef(null);

  // Close on outside click
  useEffect(() => {
    const handler = (e) => {
      if (ref.current && !ref.current.contains(e.target)) setOpen(false);
    };
    document.addEventListener("mousedown", handler);
    return () => document.removeEventListener("mousedown", handler);
  }, []);

  const exportMarkdown = () => {
    setExporting(true);
    try {
      const md = generateMarkdown(reviewResult, repoMeta, lang);
      const repoName = (repoMeta?.path || "review").split(/[/\\]/).pop();
      const date = new Date().toISOString().slice(0, 10);
      downloadFile(md, `repomind-${repoName}-${date}.md`, "text/markdown");
      setOpen(false);
    } finally {
      setExporting(false);
    }
  };

  const exportPDF = async () => {
    setExporting(true);
    try {
      // Backend gera PDF a partir do markdown
      const md = generateMarkdown(reviewResult, repoMeta, lang);
      const repoName = (repoMeta?.path || "review").split(/[/\\]/).pop();
      const date = new Date().toISOString().slice(0, 10);

      const API = window.location.port === "5173" ? "http://localhost:8000" : "";

      const r = await fetch(`${API}/export/pdf`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          markdown: md,
          title: `RepoMind Review - ${repoName}`,
        }),
      });

      if (!r.ok) {
        alert(`PDF export failed: ${r.status}`);
        return;
      }

      const blob = await r.blob();
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `repomind-${repoName}-${date}.pdf`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      setTimeout(() => URL.revokeObjectURL(url), 100);
      setOpen(false);
    } catch (err) {
      console.error("PDF export error:", err);
      alert(`Erro: ${err.message}`);
    } finally {
      setExporting(false);
    }
  };

  return (
    <div ref={ref} style={{ position: "relative", display: "inline-block" }}>
      <button
        onClick={() => setOpen(!open)}
        disabled={exporting}
        style={{
          background: "transparent",
          color: accent,
          border: `1px solid ${accent}50`,
          padding: "8px 16px",
        }}
      >
        {exporting ? t("exporting") : `↓ ${t("export")}`}
      </button>

      {open && !exporting && (
        <div style={{
          position: "absolute",
          top: "calc(100% + 4px)",
          right: 0,
          background: "#0d0d0d",
          border: "1px solid #222",
          borderRadius: 6,
          minWidth: 160,
          zIndex: 100,
          boxShadow: "0 8px 24px rgba(0,0,0,0.4)",
          overflow: "hidden",
        }}>
          <button
            onClick={exportMarkdown}
            style={{
              display: "block",
              width: "100%",
              padding: "10px 14px",
              background: "transparent",
              color: "#e8e8e8",
              border: "none",
              textAlign: "left",
              fontSize: 12,
              borderRadius: 0,
              letterSpacing: "0.04em",
            }}
            onMouseEnter={e => e.target.style.background = "#1a1a1a"}
            onMouseLeave={e => e.target.style.background = "transparent"}
          >
            📄 {t("export_md")}
          </button>
          <button
            onClick={exportPDF}
            style={{
              display: "block",
              width: "100%",
              padding: "10px 14px",
              background: "transparent",
              color: "#e8e8e8",
              border: "none",
              borderTop: "1px solid #1a1a1a",
              textAlign: "left",
              fontSize: 12,
              borderRadius: 0,
              letterSpacing: "0.04em",
            }}
            onMouseEnter={e => e.target.style.background = "#1a1a1a"}
            onMouseLeave={e => e.target.style.background = "transparent"}
          >
            📑 {t("export_pdf")}
          </button>
        </div>
      )}
    </div>
  );
}
